version: '3'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: reviro
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
